// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

// User defines model for User.
type User struct {
	// Id ID
	Id string `json:"id"`

	// Name ユーザー名
	Name string `json:"name"`
}

// V1GetUsersResponse defines model for V1GetUsersResponse.
type V1GetUsersResponse struct {
	User User `json:"user"`
}

// V1PostUsersRequest defines model for V1PostUsersRequest.
type V1PostUsersRequest struct {
	Name string `json:"name"`
}

// V1PostUsersResponse defines model for V1PostUsersResponse.
type V1PostUsersResponse struct {
	User User `json:"user"`
}

// V1PutUsersRequest defines model for V1PutUsersRequest.
type V1PutUsersRequest struct {
	Name string `json:"name"`
}

// V1PutUsersResponse defines model for V1PutUsersResponse.
type V1PutUsersResponse struct {
	User User `json:"user"`
}

// V1DeleteUsersParams defines parameters for V1DeleteUsers.
type V1DeleteUsersParams struct {
	// Id ユーザーID
	Id string `form:"id" json:"id"`
}

// V1GetUsersParams defines parameters for V1GetUsers.
type V1GetUsersParams struct {
	// Id ユーザーID
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// V1PutUsersParams defines parameters for V1PutUsers.
type V1PutUsersParams struct {
	// Id ユーザーID
	Id string `form:"id" json:"id"`
}

// V1PostUsersJSONRequestBody defines body for V1PostUsers for application/json ContentType.
type V1PostUsersJSONRequestBody = V1PostUsersRequest

// V1PutUsersJSONRequestBody defines body for V1PutUsers for application/json ContentType.
type V1PutUsersJSONRequestBody = V1PutUsersRequest
